version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: template_next
    ports:
      - '3000:3000'
    volumes:
      - .:/workspace
      - /workspace/node_modules
    environment:
      - NODE_ENV=development
